theme: jekyll-theme-minimal
title: Total Hardware 2019
description: Open source hardware encyclopedia
include: ['_pages']
google_analytics: UA-136308596-1
show_downloads: true
tipue_search:
  include:
    pages: true